# Generated by Django 5.2.16 on 2026-07-08 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tecnico', models.ForeignKey(db_column='id_tecnico', on_delete=django.db.models.deletion.RESTRICT, to='usuarios.tecnicoti')),
            ],
            options={
                'verbose_name': 'Solución',
                'verbose_name_plural': 'Soluciones',
                'db_table': 'solucion',
            },
        ),
    ]
