# Generated by Django 5.2.16 on 2026-07-08 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('COLABORADOR', 'Colaborador'), ('TECNICO', 'Técnico TI'), ('ADMINISTRADOR', 'Administrador')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('persona', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_admin', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nivel_acceso', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('persona', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_colaborador', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('estado_cuenta', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'db_table': 'colaborador',
            },
        ),
        migrations.CreateModel(
            name='TecnicoTI',
            fields=[
                ('persona', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_tecnico', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('especialidad', models.CharField(max_length=100)),
                ('disponibilidad', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tecnico TI',
                'verbose_name_plural': 'Tecnicos TI',
                'db_table': 'tecnico_ti',
            },
        ),
    ]
