# Generated by Django 5.2.16 on 2026-07-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('contenido', models.TextField()),
                ('icono', models.CharField(default='📄', max_length=10)),
                ('autor', models.CharField(default='Soporte Técnico', max_length=100)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'articulo',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
