# Generated by Django 5.2.16 on 2026-07-08 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historial', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestado',
            name='estado_anterior',
            field=models.ForeignKey(blank=True, db_column='id_estado_anterior', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='historial_como_anterior', to='tickets.estadoticket'),
        ),
        migrations.AddField(
            model_name='historialestado',
            name='estado_nuevo',
            field=models.ForeignKey(db_column='id_estado_nuevo', on_delete=django.db.models.deletion.RESTRICT, related_name='historial_como_nuevo', to='tickets.estadoticket'),
        ),
        migrations.AddField(
            model_name='historialestado',
            name='ticket',
            field=models.ForeignKey(db_column='id_ticket', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='historialestado',
            name='usuario_cambio',
            field=models.ForeignKey(db_column='usuario_cambio', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
